name: latest_movies_state_management
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  built_value: ^8.1.0
  built_collection: ^5.1.0
  http: ^0.13.3
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.5
  built_value_generator: ^8.1.0
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true